import { Button, Grid, Stack } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";
import { useDispatch, useSelector } from "react-redux";
import { AppDipatch, RootState } from "./_app";
import { Add, Remove } from "@mui/icons-material";
import { decrement, increment } from "../redux/modules/counter";

// Using Emotion Styled Component to add custom style to h1 tag.
const CustomTitle = styled.h1`
  color: #212121;
  font-family: "Open Sans", Arial, sans-serif;
  font-size: 40px;
  font-weight: bold;
`;

const Count = styled.h1`
  color: #424242;
  font-weight: bold;
  font-size: 80px;
  font-family: "Open Sans";
`;

const Counter: NextPage = () => {
  const count = useSelector((state: RootState) => state.counter.count);
  const dispatch = useDispatch<AppDipatch>();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container direction="row" justifyContent="center">
        <Grid item xs={12}>
          <Stack spacing={5} alignItems="center">
            <CustomTitle>Counter</CustomTitle>
            <CustomTitle className="counter">{count}</CustomTitle>
          </Stack>
        </Grid>
        <Grid item marginTop={10}>
          <Stack
            direction="row"
            justifyContent="center"
            alignItems="center"
            spacing={5}
          >
            <Button
              variant="outlined"
              startIcon={<Remove />}
              onClick={() => dispatch(decrement())}
            >
              Decrement
            </Button>
            <Button
              variant="outlined"
              startIcon={<Add />}
              onClick={() => dispatch(increment())}
            >
              Increment
            </Button>
          </Stack>
        </Grid>
      </Grid>
    </div>
  );
};

export default Counter;
