import {
  Button,
  Container,
  Grid,
  Paper,
  TextField,
  Typography,
} from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import AddIcon from "@mui/icons-material/Add";
import Link from "next/link";
import { Add } from "@mui/icons-material";
import { Box } from "@mui/system";
import AddNote from "../components/Home/AddNote";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper
        sx={{
          margin: "auto",
          maxWidth: { xs: "90%", md: "75%", lg: "65%" },
          padding: "25px",
          marginTop: "50px",
        }}
      >
        <AddNote />
      </Paper>
    </div>
  );
};

export default Home;
