import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import AddIcon from "@mui/icons-material/Add";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/counter">
        <Button variant="outlined" startIcon={<AddIcon />}>
          Counter Page
        </Button>
      </Link>
    </div>
  );
};

export default Home;
