import {
  Button,
  Card,
  CardActions,
  CardContent,
  Grid,
  Paper,
  Stack,
  Typography,
} from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import AddNote from "../components/Home/AddNote";
import { useSelector } from "react-redux";
import { RootState } from "./_app";

const Home: NextPage = () => {
  const notes = useSelector((state: RootState) => state.notes.notes);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        direction="column"
        sx={{
          margin: "auto",
          maxWidth: { xs: "90%", md: "75%", lg: "65%" },
          marginTop: "50px",
        }}
      >
        <Paper sx={{ padding: "25px" }}>
          <AddNote />
        </Paper>
        <Grid
          container
          direction="row"
          justifyContent="center"
          alignItems="center"
          spacing={2}
          sx={{ marginTop: "30px" }}
        >
          {notes.map((note) => (
            <Grid item xs={12} md={6} key={note.id}>
              <Card>
                <CardContent>
                  <Typography
                    sx={{ fontSize: 19, fontWeight: 600 }}
                    color="text.secondary"
                    variant="h5"
                    component="h5"
                    gutterBottom
                  >
                    {note.title}
                  </Typography>
                  <Typography variant="body1" component="p">
                    {note.content}
                  </Typography>
                </CardContent>
                <CardActions>
                  <Button size="small">Learn More</Button>
                </CardActions>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Stack>
    </div>
  );
};

export default Home;
